<!-- Start of navbar -->
<link rel="stylesheet" href="views/inc/css/app-navbar.css">
<nav class="navbar hidden-md-down navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="index.php" target="_self">Dolphin</a>
  
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item ml-auto">
        <form action="server.php" method="POST"><button type="submit" class="btn btn-secondary" name="logout_btn"><i class='fa fa-sign-out'></i> Sign Out</button>
      </li>
    </ul>
  </div>
</nav>
<!-- End of NavBar -->

<!-- Fixed options button for mobile -->
<div class="options-btn-con hidden-lg-up">
  <div class="options-btn">
    <span><i class="fa fa-list"></i></span>
  </div>
</div>


