<?php

session_start();
$username = '';
$email = '';
$errors = array();

# Connect to the database
$db = mysqli_connect(getenv('IP'), getenv('C9_USER'), '', 'c9', 3306);

# Register user
if (isset($_POST['register_btn'])) {
    $first_name = $db->real_escape_string($_POST['first_name']);
    $last_name = $db->real_escape_string($_POST['last_name']);
    $username = $db->real_escape_string($_POST['username']);
    $password = $db->real_escape_string($_POST['password']);
    $verify_pass = $db->real_escape_string($_POST['verify_pass']);
    $email = $db->real_escape_string($_POST['email']);
    
    # Making sure fields are not empty
    if ($username == '' OR $username == ' ') {
        $errors[] = 'Username is required.';
    }
    if ($password == '' OR $password == ' ') {
        $errors[] = 'Password is required.';
    }
    if ($email == '' OR $email == ' ') {
        $errors[] = 'An email is required.';
    }
    
    # Making sure passwords match
    if ($password != $verify_pass) {
        $errors[] = 'Passwords do not match.';
    }
    
    # If no errors, save user to database
    if (count($errors == 0)) {
        # Hashes password for security
        $password = md5($password);
        $sql = "INSERT INTO users (first_name, last_name, username, password, email) VALUES ('$first_name', '$last_name', '$username', '$password', '$email')";
        
        # Actual SQL injection
        mysqli_query($db, $sql);
        
        $_SESSION['username'] = $username;
        $_SESSION['first_name'] = $first_name;
        $_SESSION['success'] = 'You are now logged in as ' . $username . '.';
        header('location: dashboard.php');
    }
}



# Logout 
if (isset($_GET['logout'])) {
    session_destroy();
    unset($_SESSION['username']);
    unset($_SESSION['first_name']);
    header('location: login.php');
}


?>